### PR TITLE
Fix leaves and fruit not decaying properly ;  Fixed wield and inventory images for leaves

### PR DESCRIPTION
**Pull request by oversword**
Fix leaves and fruit not decaying properly - had to hack some param2 values for this but I feel it's justified;
Also made fruit drop on touch with attached_node, this may be annoying but it is consistent with moretrees and also reality;
Fixed wield and inventory images for leaves by removing values - allows the game to gen the 3D image;
Fixed plumtree deleting the node below it

### CODE REVIEW

**Comment by oversword** [comment]
Fixes https://github.com/BlockySurvival/issue-tracker/issues/202

**Comment by oversword** [comment]
@fluxionary I don't have write access, can you merge this so I can get it on the server?

**Comment by fluxionary** [comment]
@oversword i think i've give you write access now, can you test merging it?

**Comment by oversword** [comment]
@fluxionary thanks :) That's worked

**Pull request merged**
